#### 1. Найти с помощью NumPy SVD для матрицы

In [11]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [12]:
A=np.array([[1,2,0],[0,0,5],[3,-4,2],[1,6,5],[0,1,0]])
A

array([[ 1,  2,  0],
       [ 0,  0,  5],
       [ 3, -4,  2],
       [ 1,  6,  5],
       [ 0,  1,  0]])

In [13]:
U, s, W = np.linalg.svd(A)

# Транспонируем матрицу W
V = W.T

D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [14]:
print(f'Матрица A:\n{A}')
print(f'Матрица U:\n{U}')
print(f'Матрица D:\n{D}')
print(f'Матрица V:\n{V}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]
Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]
Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]
Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [15]:
# Проверка на ортогональность
print(np.dot(U.T, U))

[[ 1. -0.  0.  0.  0.]
 [-0.  1. -0. -0. -0.]
 [ 0. -0.  1. -0. -0.]
 [ 0. -0. -0.  1. -0.]
 [ 0. -0. -0. -0.  1.]]


In [16]:
# Проверка на ортогональность
print(np.dot(V.T, V))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
# Проведем проверку
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2. -0.]
 [-0.  0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [ 0.  1.  0.]]


##### 2. Для матрицы из предыдущего задания найти:

а) евклидову норму;

б) норму Фробениуса.

In [23]:
print(f'Норма Евклида для матрицы А: ')
np.linalg.norm(A, ord=2)

Норма Евклида для матрицы А: 


8.824868854820442

In [26]:
print(f"Норма Фробениуса для матрицы A:\n{np.linalg.norm(A, ord='fro')}")

Норма Фробениуса для матрицы A:
11.045361017187261
